version: "3.4"

services:
  infinitereserveservice:
    image: infinitereserveservice
    container_name: infinitereserveservice
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010/api
      AI_API: http://infinitereserveai.docker:5003/api
      ONEAUTH_API_KEY: 78b4e61d-de91-4700-9404-3a9a0924ba8a
      PORT: 8025
    ports:
      - 8025:8025
    networks:
      ioak-net:
        aliases:
          - infinitereserveservice.docker

networks:
  ioak-net:
    external: true
